### PR TITLE
Use Jinja template engine

### PR DESCRIPTION
**Pull request by yohanesgultom**
Use Jinja to render the HTML to decouple logic from presentation. Hopefully this will make it easier for others to contribute on the design aspect

### CODE REVIEW

**Comment by Adarsh-Goel** [comment]
i see

**Comment by Adarsh-Goel** [comment]
this won't help sadly

**Comment by Adarsh-Goel** [comment]
this project uses actions to collect coupons and commit this but what you added won't work as action dies after committing and doesn't support domain/ip access!

**Comment by Adarsh-Goel** [comment]
changes made such that action runs and commits to index.html will be appreciated thanks for your interest :D

**Comment by Adarsh-Goel** [comment]
if you add index.html to templates directory I don't think github pages will render it 
Though if I am wrong please clarify

**Comment by Adarsh-Goel** [comment]
> Hi @Adarsh-Goel . So this PR is actually just extracting your hard-coded html into a separate file, namely `templates/index.html`. When you run the `app.py`, it will still generate the same `index.html` in the root directory just like before.
> 
> But if you think this will not help, feel free to ignore it. I will try to propose other improvements (eg. automated test) that may suit your preference better.

Ok I will review it again then!

**Review by Adarsh-Goel — APPROVED** [review]
I am approving it incase it doesn't work I'll revert.

**Comment by Adarsh-Goel** [comment]
your pull request has been merged and its working fine!
I have a query earlier all coupons were earlier committed to main branch now i switched them to gh-pages branch anyway to delete those commits?

**Comment by yohanesgultom** [comment]
Thanks for accepting my PR again.

I assume you are referring to the `[AUTOMATED] Updated Website With Fresh Coupons` commits? You can edit the history using `git rebase` or just delete/reinit `.git` subdir. After then you need to do a `git push -f origin main`

**Pull request merged**
